### ISSUE TITLE
mysql_statsd listens on UDP:20981 - why?

### ISSUE THREAD

**Issue by darookee** [spilgames/mysql-statsd#25]
I installed mysql_statsd via pip and just noticed that when it runs it listens on *:20981 - why does it do that? I cannot find anything in the code or in the docs to indicate that it listens for anything.
Also is there a way to bind it to a specifig IP?

**Comment by thijsdezoete** [comment]
Hi @darookee thanks for your questions.
As for the "is there any way to bind it to a specific ip" question, could you clarify a bit more what you mean with "it" in this case? mysql statsd is built with a couple components, and I would like to understand what your question is about. What are you trying to achieve, or which problems are you running into which led you to these questions.

Thanks in advance!

**Comment by darookee** [comment]
@art-spilgames Thanks for the insight, I normaly use lsof to check for open ports and I overlooked that it says '(LISTEN)' after the portnumber when displaying actual listening ports.
I'll close this... :-)
