### ISSUE TITLE
ThreadStatsd crashes when mysql replication thread is stopped

### ISSUE THREAD

**Issue by Exus** [spilgames/mysql-statsd#30]
ThreadStatsd is crashing when SQL Slave is down, because slave.seconds_behind_master is Null

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/ex/mysql-statsd/mysql_statsd/thread_statsd.py", line 71, in run
    self.send_stat(item)
  File "/home/ex/mysql-statsd/mysql_statsd/thread_statsd.py", line 55, in send_stat
    sender(k, float(v))
TypeError: float() argument must be a string or a number

Here is workaround:
           try:
                sender(k, float(v))
           except Exception, e:
                print "k", k, "v", v
                print e

$ python mysql_statsd/mysql_statsd.py -d -f -c ~ex/mysql-statsd.conf
k slave.seconds_behind_master v None
float() argument must be a string or a number

**Comment by art-spilgames** [comment]
Hi Exus,

Thanks for reporting this bug.
It is kind of expected when a NULL is sent to the sending of metric it will crash as it explicitly expects a numeric value.
I'll ask Thijs to include the exception.

Art

**Comment by thijsdezoete** [comment]
Question is, is it normal for mysql to give this value? What does that mean? Can we then maybe convert the value to 0 if it's a normal value?

**Comment by art-spilgames** [comment]
@thijsdezoete Yes it is the normal value. The value normally is the seconds the slave is lagging behind its master, however if replication breaks it uses NULL to determine it is broken.

**Comment by thijsdezoete** [comment]
Ok, and the desired action would be to not send the data(for this specific key) in the case of downtime I guess?

**Comment by thijsdezoete** [comment]
Oops, we merged this one a little soon, but I would still like to verify if this actually solves your issue @Exus

**Comment by Exus** [comment]
Yep, it's fine now

Thanks!
